import { Inter } from "next/font/google";
import "./globals.css";
import Nevbar from "./Components/Nevbar";
import Footer from "./Components/Footer";
import SassionWrapper from "./Components/SassionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className= {inter.className}> 
      <SassionWrapper>
        <Nevbar/>
        <div className="min-h-[86.25vh]  bg-[#000000] bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] bg-[size:20px_20px]">
        {children}
        </div>
        <Footer/>
        <animated/>
      </SassionWrapper>
      </body>
    </html>
  );
}
